server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
    profiles:
        active: test
  thymeleaf:
    prefix: classpath:templates/
  security:
    user:
      name: user
      password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  profiles:
    active: test
  messages:
    basename: messages,errors
  mvc:
    converters:
      preferred-json-mapper: gson
#        show_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.springframework.jdbc: debug
#image:
#  storage:
#    tempDir: /Users/siyeon/Desktop/temp/summernote_image/
#    Dir: /Users/siyeon/Desktop/summernote_image/
image:
  storage:
    tempDir: D:\temp\summernote_image\
    Dir: D:\summernote_image\
mybatis:
  type-aliases-package: com.example.demo.dto
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
