server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: user
      password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#        show_sql: true
logging.level:
  org.hibernate.SQL: debug
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/querydsl
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  messages:
#    basename: messages
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        default_batch_fetch_size: 100
#  security:
#    user:
#      name: user
#      password: 1111
#logging.level:
#  org.hibernate.SQL: debug
#logging:
#  level:
#      root: info
#  org:
#    hibernate:
#      SQL: debug
#      type:
#        descriptor:
#          sql: trace
#  pattern:
#    console: "%-5level %d{yy-MM-dd HH:mm:SSS}[%thread] %logger[%method:%line] - %msg%n"
#    file: "%-5level %d{yy-MM-dd HH:mm:SSS}[%thread] %logger[%method:%line] - %msg%n"
#  file:
#    name: C:/unistudy/logs/logback-dev.log
#  logback:
#    rollingpolicy:
#      max-file-size: 1MB                #default 10M
#      max-history: 31                   #default 7
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz